class Forum < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["encrypted_password", "password_reset_token", "comments", "user_image_attachment", "user_image_blob", "owner"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["comments", "user_image_attachment", "user_image_blob"]
    end
    enum tags: [ 
        :artificial_intelligence,
        :android,
        :art,
        :business,
        :book,
        :blockchain,
        :covid,
        :coronavirus,
        :content_marketing,
        :creativity,
        :culture,
        :crypto,
        :cryptocurrency,
        :data_science,
        :digital_marketing,
        :design,
        :entrepreneurship,
        :entrepreneur,
        :education,
        :family,
        :finance,
        :food,
        :fiction,
        :health,
        :healthcare,
        :history,
        :humor,
        :india,
        :interview,
        :life,
        :life_lessons,
        :lifestyle,
        :love,
        :marketing,
        :management,
        :mental_healt,
        :meditation,
        :mindfulness,
        :mobile,
        :movies,
        :money,
        :mobile_app_development,
        :music,
        :news,
        :programming,
        :psychology,
        :poem,
        :poetry,
        :podcast,
        :politics,
        :relationships,
        :startup,
        :self,
        :self_improvement,
        :self_awareness,
        :software_development,
        :storytelling,
        :short_story,
        :social_media,
        :social_media_marketing,
        :sports,
        :travel,
        :tech,
        :technology,
        :leadership,
        :ux,
        :ux_design,
        :writing,
        :writing_tips ]

    has_one_attached :user_image
    has_many :comments, dependent: :destroy
end
